
interface _GlobalComponents {
      'ActivityBaliFarm': typeof import("../components/ActivityBaliFarm.vue")['default']
    'BaliFarmGA': typeof import("../components/BaliFarmGA.vue")['default']
    'BaliSafariEvent': typeof import("../components/BaliSafariEvent.vue")['default']
    'BaliSafariTicket': typeof import("../components/BaliSafariTicket.vue")['default']
    'CardDaily': typeof import("../components/CardDaily.vue")['default']
    'DetailTicketAboutTicket': typeof import("../components/DetailTicket/AboutTicket.vue")['default']
    'DetailTicketAlert': typeof import("../components/DetailTicket/Alert.vue")['default']
    'DetailTicketLoader': typeof import("../components/DetailTicket/Loader.vue")['default']
    'DetailTicketInformation': typeof import("../components/DetailTicket/TicketInformation.vue")['default']
    'ExplorerSPData': typeof import("../components/ExplorerSPData.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'GeneralAdmission': typeof import("../components/GeneralAdmission.vue")['default']
    'HomeComponentBaliBirdExplore': typeof import("../components/HomeComponent/BaliBirdExplore.vue")['default']
    'HomeComponentBaliFarmExplore': typeof import("../components/HomeComponent/BaliFarmExplore.vue")['default']
    'HomeComponentBaliSafariExplore': typeof import("../components/HomeComponent/BaliSafariExplore.vue")['default']
    'HomeComponentBaliZooExplore': typeof import("../components/HomeComponent/BaliZooExplore.vue")['default']
    'HomeComponentVendorHome': typeof import("../components/HomeComponent/VendorHome.vue")['default']
    'HorizontalCard': typeof import("../components/HorizontalCard.vue")['default']
    'ImageCard': typeof import("../components/ImageCard.vue")['default']
    'ModalGeneralAdmissionModal': typeof import("../components/Modal/GeneralAdmissionModal.vue")['default']
    'ModalMapsModal': typeof import("../components/Modal/MapsModal.vue")['default']
    'ModalOpeningHourModal': typeof import("../components/Modal/OpeningHourModal.vue")['default']
    'ModalWhatsonModal': typeof import("../components/Modal/WhatsonModal.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'PanelInfo': typeof import("../components/PanelInfo.vue")['default']
    'PopularActivities': typeof import("../components/PopularActivities.vue")['default']
    'QuantitySelector': typeof import("../components/QuantitySelector.vue")['default']
    'TicketCard': typeof import("../components/TicketCard.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyActivityBaliFarm': typeof import("../components/ActivityBaliFarm.vue")['default']
    'LazyBaliFarmGA': typeof import("../components/BaliFarmGA.vue")['default']
    'LazyBaliSafariEvent': typeof import("../components/BaliSafariEvent.vue")['default']
    'LazyBaliSafariTicket': typeof import("../components/BaliSafariTicket.vue")['default']
    'LazyCardDaily': typeof import("../components/CardDaily.vue")['default']
    'LazyDetailTicketAboutTicket': typeof import("../components/DetailTicket/AboutTicket.vue")['default']
    'LazyDetailTicketAlert': typeof import("../components/DetailTicket/Alert.vue")['default']
    'LazyDetailTicketLoader': typeof import("../components/DetailTicket/Loader.vue")['default']
    'LazyDetailTicketInformation': typeof import("../components/DetailTicket/TicketInformation.vue")['default']
    'LazyExplorerSPData': typeof import("../components/ExplorerSPData.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyGeneralAdmission': typeof import("../components/GeneralAdmission.vue")['default']
    'LazyHomeComponentBaliBirdExplore': typeof import("../components/HomeComponent/BaliBirdExplore.vue")['default']
    'LazyHomeComponentBaliFarmExplore': typeof import("../components/HomeComponent/BaliFarmExplore.vue")['default']
    'LazyHomeComponentBaliSafariExplore': typeof import("../components/HomeComponent/BaliSafariExplore.vue")['default']
    'LazyHomeComponentBaliZooExplore': typeof import("../components/HomeComponent/BaliZooExplore.vue")['default']
    'LazyHomeComponentVendorHome': typeof import("../components/HomeComponent/VendorHome.vue")['default']
    'LazyHorizontalCard': typeof import("../components/HorizontalCard.vue")['default']
    'LazyImageCard': typeof import("../components/ImageCard.vue")['default']
    'LazyModalGeneralAdmissionModal': typeof import("../components/Modal/GeneralAdmissionModal.vue")['default']
    'LazyModalMapsModal': typeof import("../components/Modal/MapsModal.vue")['default']
    'LazyModalOpeningHourModal': typeof import("../components/Modal/OpeningHourModal.vue")['default']
    'LazyModalWhatsonModal': typeof import("../components/Modal/WhatsonModal.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyPanelInfo': typeof import("../components/PanelInfo.vue")['default']
    'LazyPopularActivities': typeof import("../components/PopularActivities.vue")['default']
    'LazyQuantitySelector': typeof import("../components/QuantitySelector.vue")['default']
    'LazyTicketCard': typeof import("../components/TicketCard.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ActivityBaliFarm: typeof import("../components/ActivityBaliFarm.vue")['default']
export const BaliFarmGA: typeof import("../components/BaliFarmGA.vue")['default']
export const BaliSafariEvent: typeof import("../components/BaliSafariEvent.vue")['default']
export const BaliSafariTicket: typeof import("../components/BaliSafariTicket.vue")['default']
export const CardDaily: typeof import("../components/CardDaily.vue")['default']
export const DetailTicketAboutTicket: typeof import("../components/DetailTicket/AboutTicket.vue")['default']
export const DetailTicketAlert: typeof import("../components/DetailTicket/Alert.vue")['default']
export const DetailTicketLoader: typeof import("../components/DetailTicket/Loader.vue")['default']
export const DetailTicketInformation: typeof import("../components/DetailTicket/TicketInformation.vue")['default']
export const ExplorerSPData: typeof import("../components/ExplorerSPData.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const GeneralAdmission: typeof import("../components/GeneralAdmission.vue")['default']
export const HomeComponentBaliBirdExplore: typeof import("../components/HomeComponent/BaliBirdExplore.vue")['default']
export const HomeComponentBaliFarmExplore: typeof import("../components/HomeComponent/BaliFarmExplore.vue")['default']
export const HomeComponentBaliSafariExplore: typeof import("../components/HomeComponent/BaliSafariExplore.vue")['default']
export const HomeComponentBaliZooExplore: typeof import("../components/HomeComponent/BaliZooExplore.vue")['default']
export const HomeComponentVendorHome: typeof import("../components/HomeComponent/VendorHome.vue")['default']
export const HorizontalCard: typeof import("../components/HorizontalCard.vue")['default']
export const ImageCard: typeof import("../components/ImageCard.vue")['default']
export const ModalGeneralAdmissionModal: typeof import("../components/Modal/GeneralAdmissionModal.vue")['default']
export const ModalMapsModal: typeof import("../components/Modal/MapsModal.vue")['default']
export const ModalOpeningHourModal: typeof import("../components/Modal/OpeningHourModal.vue")['default']
export const ModalWhatsonModal: typeof import("../components/Modal/WhatsonModal.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const PanelInfo: typeof import("../components/PanelInfo.vue")['default']
export const PopularActivities: typeof import("../components/PopularActivities.vue")['default']
export const QuantitySelector: typeof import("../components/QuantitySelector.vue")['default']
export const TicketCard: typeof import("../components/TicketCard.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyActivityBaliFarm: typeof import("../components/ActivityBaliFarm.vue")['default']
export const LazyBaliFarmGA: typeof import("../components/BaliFarmGA.vue")['default']
export const LazyBaliSafariEvent: typeof import("../components/BaliSafariEvent.vue")['default']
export const LazyBaliSafariTicket: typeof import("../components/BaliSafariTicket.vue")['default']
export const LazyCardDaily: typeof import("../components/CardDaily.vue")['default']
export const LazyDetailTicketAboutTicket: typeof import("../components/DetailTicket/AboutTicket.vue")['default']
export const LazyDetailTicketAlert: typeof import("../components/DetailTicket/Alert.vue")['default']
export const LazyDetailTicketLoader: typeof import("../components/DetailTicket/Loader.vue")['default']
export const LazyDetailTicketInformation: typeof import("../components/DetailTicket/TicketInformation.vue")['default']
export const LazyExplorerSPData: typeof import("../components/ExplorerSPData.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyGeneralAdmission: typeof import("../components/GeneralAdmission.vue")['default']
export const LazyHomeComponentBaliBirdExplore: typeof import("../components/HomeComponent/BaliBirdExplore.vue")['default']
export const LazyHomeComponentBaliFarmExplore: typeof import("../components/HomeComponent/BaliFarmExplore.vue")['default']
export const LazyHomeComponentBaliSafariExplore: typeof import("../components/HomeComponent/BaliSafariExplore.vue")['default']
export const LazyHomeComponentBaliZooExplore: typeof import("../components/HomeComponent/BaliZooExplore.vue")['default']
export const LazyHomeComponentVendorHome: typeof import("../components/HomeComponent/VendorHome.vue")['default']
export const LazyHorizontalCard: typeof import("../components/HorizontalCard.vue")['default']
export const LazyImageCard: typeof import("../components/ImageCard.vue")['default']
export const LazyModalGeneralAdmissionModal: typeof import("../components/Modal/GeneralAdmissionModal.vue")['default']
export const LazyModalMapsModal: typeof import("../components/Modal/MapsModal.vue")['default']
export const LazyModalOpeningHourModal: typeof import("../components/Modal/OpeningHourModal.vue")['default']
export const LazyModalWhatsonModal: typeof import("../components/Modal/WhatsonModal.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyPanelInfo: typeof import("../components/PanelInfo.vue")['default']
export const LazyPopularActivities: typeof import("../components/PopularActivities.vue")['default']
export const LazyQuantitySelector: typeof import("../components/QuantitySelector.vue")['default']
export const LazyTicketCard: typeof import("../components/TicketCard.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
